### ISSUE TITLE
Door State not shown in datapoints

### ISSUE THREAD

**Issue by FlexerJR** [DrozmotiX/ioBroker.bambulab#115]
Hello my lovely Developer of the Bambulab adapter,

i use hass io to get the state of the door of my x1c printer. Is it possible to get this state in iob as well? If yes i can delete hass.

![image](https://github.com/user-attachments/assets/3a62988c-3000-4fa3-829b-8f0a69992a6e)

**Comment by DutchmanNL** [comment]
> If yes i can delete hass.

have fun with 0.3.4 and decommissioning :)

**Comment by FlexerJR** [comment]
Kisses 💋💋

**Comment by kodibrain** [comment]
It doesn't work like that. HomeFlag is not always the same when the door is open or closed. HomeFlag always has a difference of 8388608 between open and closed. I have made a pull request with the necessary changes to make it work
https://github.com/DrozmotiX/ioBroker.bambulab/pull/132
