### ISSUE TITLE
Error on Adapter restart HMS JSON request

### ISSUE THREAD

**Issue by vr6syncro** [DrozmotiX/ioBroker.bambulab#18]
`[loadHMSerroCodeTranslations] TypeError: currentTranObj.ver.toUpperCase is not a function | TypeError: currentTranObj.ver.toUpperCase is not a function at Bambulab.loadHMSerrorCodeTranslations (/opt/iobroker/node_modules/iobroker.bambulab/main.js:435:60) at async Bambulab.onReady (/opt/iobroker/node_modules/iobroker.bambulab/main.js:54:3)`

https://e.bambulab.com/query.php?lang=de

Die seite ist aber erreichbar.

**Comment by vr6syncro** [comment]
das weiß ich nicht... su wolltest das ich das issue auf mache und irgendwas ändern ;)

**Comment by DutchmanNL** [comment]
got the answer, still required and slightly improved in 0.3.0
