### ISSUE TITLE
Falsches Datenformat

### ISSUE THREAD

**Issue by spoeh-man** [DrozmotiX/ioBroker.bambulab#19]
Ich bekomme immer folgende Meldungen über falsche formate

`

bambulab.0 | 2023-08-26 19:26:06.041 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.3.bed_temp" has to be type "number" but received type "string"
-- | -- | -- | --
bambulab.0 | 2023-08-26 19:26:06.040 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.2.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:26:06.039 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.1.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:26:06.037 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.0.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:55.878 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.3.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:55.877 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.2.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:55.835 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.1.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:55.832 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.0.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:50.836 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.3.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:50.834 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.2.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:50.791 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.1.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:50.789 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.0.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:45.770 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.3.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:45.769 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.2.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:45.767 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.1.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-08-26 19:25:45.765 | info | State value to set for "bambulab.0.00M09A341101970.ams.ams.0.tray.0.bed_temp" has to be type "number" but received type "string"

`

**Comment by DutchmanNL** [comment]
koennte du mir mal bitte die werte der Datenpunkte schicken, verstehen nicht warum du einen string bei temperaturen bekommst
