### ISSUE TITLE
Bambulab P1S

### ISSUE THREAD

**Issue by DerT94** [DrozmotiX/ioBroker.bambulab#25]
Hey,

got a brand new Bambulab P1S.

The Adapter seems to work. Are there any special details that I can test?

**Comment by DutchmanNL** [comment]
> Hey,
> 
> got a brand new Bambulab P1S.
> 
> The Adapter seems to work. Are there any special details that I can test?

basically the generic things :)

- do all values correspond with your values in Bambulab studio
- is the connection working
- any feedback on datapoints created/updated

would be appreciated :)

**Comment by DutchmanNL** [comment]
@DerT94 there is one thing you can test for me :)

I need to know if polling is still needed for the P1 series, can you please try to set th printer type (adapter settings) to X1 or XC1 and let us know if you still receive all data frequently ?
