### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by Azathoth88** [DrozmotiX/ioBroker.bambulab#26]
I'm printing and I get the following error message in the log:

Node.js
v18.17.1

NPM
9.6.7

[messageHandler] TypeError: Cannot read properties of undefined (reading 'ams') \| TypeError: Cannot read properties of undefined (reading 'ams') at Bambulab.messageHandler (/opt/iobroker/node_modules/iobroker.bambulab/main.js:199:57) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.bambulab/main.js:107:11) at MqttClient.emit (node:events:514:28) at MqttClient._handlePublish (/opt/iobroker/node_modules/mqtt/lib/client.js:1547:12) at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:535:12) at work (/opt/iobroker/node_modules/mqtt/lib/client.js:438:12) at writable._write (/opt/iobroker/node_modules/mqtt/lib/client.js:452:5) at doWrite (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139) at writeOrBuffer (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5) at Writable.write (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)

**Comment by DutchmanNL** [comment]
hmm it looks like you don't have an AMS right ? what kin dof printer model are you using with which firmware ?

**Comment by Azathoth88** [comment]
I have an X1-Carbon with AMS.

Latest Firmware
X1-Carbon: 01.06.05.01
AMS: 00.00.06.40

**Comment by DutchmanNL** [comment]
> I have an X1-Carbon with AMS.
> 
> Latest Firmware X1-Carbon: 01.06.05.01 AMS: 00.00.06.40

hmm did you try newest version from ? I cannot reproduce this with my xc1 and latest firmware
