### ISSUE TITLE
Keine Daten vom x1c

### ISSUE THREAD

**Issue by Webranger2** [DrozmotiX/ioBroker.bambulab#27]
Alle Daten eingetragen und der Adapter wird auch grün aber empfängt keine Daten vom x1c. 

Fehler kommt auch nicht

**Comment by djalexz** [comment]
Nabend, hast du den Adapter mal auf Debug gestellt und dann nochmal im Log geschaut?

**Comment by Webranger2** [comment]
War mein Fehler. Gerade das problem gefunden und jetzt kommen daten.
Trotz copy&past einen fehler in der Seriennummer gehabt.

**Comment by Webranger2** [comment]
Kann somit zu
