### ISSUE TITLE
Chamber Fan & Nozzle Fan zeigen 8% wenn 60% am Drucker eingestellt sind

### ISSUE THREAD

**Issue by XSDiVer** [DrozmotiX/ioBroker.bambulab#36]
Das Problem hat der Aux Fan scheinbar nicht,
da stimmen die Werte.

**Comment by DutchmanNL** [comment]
hmm, kan es sein das da andere werte kommen (adapter auf debug stellen) die FAN speed werden hier übersetzt:

https://github.com/DrozmotiX/ioBroker.bambulab/blob/main/lib/converter.js#L2-L65

**Comment by Matzebhv** [comment]
Das Problem habe ich beim X1C tatsächlich auch:
3 Lüfter sind verbaut, bei dem derzeit laufenden Job:
Nozzle: 100%
Aux: 70%
Chamb: 0%

Unter den Objekten befinden sich:

heatbreak_fan_speed: 14%
cooling_fan_speed: 100%
big_fan1_speed: 70%
fanSpeedChamber: 0 ohne %

Mir scheint hier die Zuordnung der Lüfter zu den DP nicht zu passen, es sind auch nur 3 Lüfter verbaut und hier sind 4 DP vorhanden.

`Response of JSONexploer: {"00M09A371200669.command":{"modify":"","name":"command","type":"string","role":"state","read":true,"write":false,"value":"push_status"},"00M09A371200669.msg":{"modify":"","name":"msg","type":"number","role":"state","read":true,"write":false,"value":1},"00M09A371200669.sequence_id":{"modify":"","name":"sequence_id","type":"string","role":"state","read":true,"write":false,"value":"56339"},"00M09A371200669.t_utc":{"modify":"","name":"t_utc","type":"number","role":"state","read":true,"write":false,"value":1697967634634},"00M09A371200669.heatbreak_fan_speed":{"modify":["toNumber"],"name":"Heatbreak fan Speed","type":"number","role":"level","read":true,"write":false,"unit":"%","value":14},"00M09A371200669.control.heatbreak_fan_speed":{"modify":["toNumber"],"name":"Heatbreak fan Speed","type":"number","role":"level","read":true,"write":false,"unit":"%","value":14},"00M09A371200669.hms.hmsErrorCount":{"modify":"","name":"hmsErrorCount","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.hms.hmsErrors":{"modify":"","name":"hmsErrors","type":"boolean","role":"state","read":true,"write":false,"value":false},"00M09A371200669.mc_remaining_time":{"modify":"","name":"Remaining Time","type":"string","role":"value.time","read":true,"write":false,"value":"05:51"},"00M09A371200669.layer_num":{"modify":"","name":"layer_num","type":"number","role":"state","read":true,"write":false,"value":5},"00M09A371200669.home_flag":{"modify":"","name":"home_flag","type":"number","role":"state","read":true,"write":false,"value":118207},"00M09A371200669.wifi_signal":{"modify":"","name":"wifi_signal","type":"string","role":"state","read":true,"write":false,"value":"-42dBm"},"00M09A371200669.mc_percent":{"modify":["toNumber"],"name":"Printjob finish in percent","type":"number","role":"level","read":true,"write":false,"unit":"%","value":4},"00M09A371200669.chamber_temper":{"modify":["toNumber"],"name":"Chamber Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":31},"00M09A371200669.nozzle_temper":{"modify":["toNumber"],"name":"Nozzle current Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":220},"00M09A371200669.ipcam.tutk_server":{"modify":"","name":"tutk_server","type":"string","role":"state","read":true,"write":false,"value":"enable"},"00M09A371200669.print_gcode_action":{"modify":"","name":"print_gcode_action","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.stg_cur":{"modify":"","name":"Stage Parser","type":"string","role":"state","read":true,"write":false,"value":"Printing"},"00M09A371200669.control.stg_cur":{"modify":"","name":"Stage Parser","type":"string","role":"state","read":true,"write":false,"value":"Printing"},"00M09A371200669.fan_gear":{"modify":"","name":"fan_gear","type":"number","role":"state","read":true,"write":false,"value":45823},"00M09A371200669.big_fan1_speed":{"modify":["toNumber"],"name":"AUX Fan 1 Speed","type":"number","role":"level","read":true,"write":true,"unit":"%","value":70},"00M09A371200669.cooling_fan_speed":{"modify":["toNumber"],"name":"Cooling fan Speed","type":"number","role":"level","read":true,"write":true,"unit":"%","value":100},"00M09A371200669.control.cooling_fan_speed":{"modify":["toNumber"],"name":"Cooling fan Speed","type":"number","role":"level","read":true,"write":true,"unit":"%","value":100},"00M09A371200669.control.big_fan1_speed":{"modify":["toNumber"],"name":"AUX Fan 1 Speed","type":"number","role":"level","read":true,"write":true,"unit":"%","value":70},"00M09A371200669.ams.tray_tar":{"modify":"","name":"tray_tar","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams_status":{"modify":"","name":"ams_status","type":"number","role":"state","read":true,"write":false,"value":768},"00M09A371200669.mc_print_sub_stage":{"modify":"","name":"mc_print_sub_stage","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.print_real_action":{"modify":"","name":"print_real_action","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.bed_target_temper":{"modify":["toNumber"],"name":"Bed Target Temperature","type":"number","role":"level.temperature","read":true,"write":true,"unit":"°C","value":35},"00M09A371200669.control.bed_target_temper":{"modify":["toNumber"],"name":"Bed Target Temperature","type":"number","role":"level.temperature","read":true,"write":true,"unit":"°C","value":35},"00M09A371200669.hw_switch_state":{"modify":"","name":"hw_switch_state","type":"number","role":"state","read":true,"write":false,"value":1},"00M09A371200669.ams.tray_now":{"modify":"","name":"tray_now","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.tray_pre":{"modify":"","name":"tray_pre","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.nozzle_target_temper":{"modify":["toNumber"],"name":"Nozzle target Temperature","type":"number","role":"level.temperature","read":true,"write":true,"unit":"°C","value":220},"00M09A371200669.control.nozzle_target_temper":{"modify":["toNumber"],"name":"Nozzle target Temperature","type":"number","role":"level.temperature","read":true,"write":true,"unit":"°C","value":220},"00M09A371200669.ams.ams.0.humidity":{"modify":"","name":"humidity","type":"string","role":"state","read":true,"write":false,"value":"5"},"00M09A371200669.ams.ams.0.id":{"modify":"","name":"id","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.temp":{"modify":"","name":"temp","type":"string","role":"state","read":true,"write":false,"value":"32.7"},"00M09A371200669.ams.ams.0.tray.0.bed_temp_type":{"modify":"","name":"bed_temp_type","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.0.cali_idx":{"modify":"","name":"cali_idx","type":"number","role":"state","read":true,"write":false,"value":376},"00M09A371200669.ams.ams.0.tray.0.cols":{"modify":"","name":"cols","type":"string","role":"state","read":true,"write":false,"value":"[\"161616FF\"]"},"00M09A371200669.ams.ams.0.tray.0.ctype":{"modify":"","name":"ctype","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.ams.ams.0.tray.0.drying_temp":{"modify":"","name":"drying_temp","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.0.drying_time":{"modify":"","name":"drying_time","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.0.id":{"modify":"","name":"id","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.0.nozzle_temp_max":{"modify":"","name":"nozzle_temp_max","type":"string","role":"state","read":true,"write":false,"value":"240"},"00M09A371200669.ams.ams.0.tray.0.nozzle_temp_min":{"modify":"","name":"nozzle_temp_min","type":"string","role":"state","read":true,"write":false,"value":"190"},"00M09A371200669.ams.ams.0.tray.0.remain":{"modify":"","name":"remain","type":"number","role":"state","read":true,"write":false,"value":-1},"00M09A371200669.ams.ams.0.tray.0.tag_uid":{"modify":"","name":"tag_uid","type":"string","role":"state","read":true,"write":false,"value":"0000000000000000"},"00M09A371200669.ams.ams.0.tray.0.tray_color":{"modify":"","name":"tray_color","type":"string","role":"state","read":true,"write":false,"value":"161616FF"},"00M09A371200669.ams.ams.0.tray.0.tray_diameter":{"modify":"","name":"tray_diameter","type":"string","role":"state","read":true,"write":false,"value":"0.00"},"00M09A371200669.ams.ams.0.tray.0.tray_id_name":{"modify":"","name":"tray_id_name","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.0.tray_info_idx":{"modify":"","name":"tray_info_idx","type":"string","role":"state","read":true,"write":false,"value":"GFL99"},"00M09A371200669.ams.ams.0.tray.0.tray_sub_brands":{"modify":"","name":"tray_sub_brands","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.0.tray_type":{"modify":"","name":"tray_type","type":"string","role":"state","read":true,"write":false,"value":"PLA"},"00M09A371200669.ams.ams.0.tray.0.tray_uuid":{"modify":"","name":"tray_uuid","type":"string","role":"state","read":true,"write":false,"value":"00000000000000000000000000000000"},"00M09A371200669.ams.ams.0.tray.0.tray_weight":{"modify":"","name":"tray_weight","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.0.xcam_info":{"modify":"","name":"xcam_info","type":"string","role":"state","read":true,"write":false,"value":"000000000000000000000000"},"00M09A371200669.ams.ams.0.tray.1.bed_temp_type":{"modify":"","name":"bed_temp_type","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.1.cali_idx":{"modify":"","name":"cali_idx","type":"number","role":"state","read":true,"write":false,"value":767},"00M09A371200669.ams.ams.0.tray.1.cols":{"modify":"","name":"cols","type":"string","role":"state","read":true,"write":false,"value":"[\"FFFFFFFF\"]"},"00M09A371200669.ams.ams.0.tray.1.ctype":{"modify":"","name":"ctype","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.ams.ams.0.tray.1.drying_temp":{"modify":"","name":"drying_temp","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.1.drying_time":{"modify":"","name":"drying_time","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.1.id":{"modify":"","name":"id","type":"string","role":"state","read":true,"write":false,"value":"1"},"00M09A371200669.ams.ams.0.tray.1.nozzle_temp_max":{"modify":"","name":"nozzle_temp_max","type":"string","role":"state","read":true,"write":false,"value":"240"},"00M09A371200669.ams.ams.0.tray.1.nozzle_temp_min":{"modify":"","name":"nozzle_temp_min","type":"string","role":"state","read":true,"write":false,"value":"190"},"00M09A371200669.ams.ams.0.tray.1.remain":{"modify":"","name":"remain","type":"number","role":"state","read":true,"write":false,"value":-1},"00M09A371200669.ams.ams.0.tray.1.tag_uid":{"modify":"","name":"tag_uid","type":"string","role":"state","read":true,"write":false,"value":"0000000000000000"},"00M09A371200669.ams.ams.0.tray.1.tray_color":{"modify":"","name":"tray_color","type":"string","role":"state","read":true,"write":false,"value":"FFFFFFFF"},"00M09A371200669.ams.ams.0.tray.1.tray_diameter":{"modify":"","name":"tray_diameter","type":"string","role":"state","read":true,"write":false,"value":"0.00"},"00M09A371200669.ams.ams.0.tray.1.tray_id_name":{"modify":"","name":"tray_id_name","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.1.tray_info_idx":{"modify":"","name":"tray_info_idx","type":"string","role":"state","read":true,"write":false,"value":"GFL99"},"00M09A371200669.ams.ams.0.tray.1.tray_sub_brands":{"modify":"","name":"tray_sub_brands","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.1.tray_type":{"modify":"","name":"tray_type","type":"string","role":"state","read":true,"write":false,"value":"PLA"},"00M09A371200669.ams.ams.0.tray.1.tray_uuid":{"modify":"","name":"tray_uuid","type":"string","role":"state","read":true,"write":false,"value":"00000000000000000000000000000000"},"00M09A371200669.ams.ams.0.tray.1.tray_weight":{"modify":"","name":"tray_weight","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.1.xcam_info":{"modify":"","name":"xcam_info","type":"string","role":"state","read":true,"write":false,"value":"000000000000000000000000"},"00M09A371200669.ams.ams.0.tray.2.id":{"modify":"","name":"id","type":"string","role":"state","read":true,"write":false,"value":"2"},"00M09A371200669.ams.ams.0.tray.3.bed_temp_type":{"modify":"","name":"bed_temp_type","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.3.cali_idx":{"modify":"","name":"cali_idx","type":"number","role":"state","read":true,"write":false,"value":-1},"00M09A371200669.ams.ams.0.tray.3.cols":{"modify":"","name":"cols","type":"string","role":"state","read":true,"write":false,"value":"[\"898989FF\"]"},"00M09A371200669.ams.ams.0.tray.3.ctype":{"modify":"","name":"ctype","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.ams.ams.0.tray.3.drying_temp":{"modify":"","name":"drying_temp","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.3.drying_time":{"modify":"","name":"drying_time","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.3.id":{"modify":"","name":"id","type":"string","role":"state","read":true,"write":false,"value":"3"},"00M09A371200669.ams.ams.0.tray.3.nozzle_temp_max":{"modify":"","name":"nozzle_temp_max","type":"string","role":"state","read":true,"write":false,"value":"240"},"00M09A371200669.ams.ams.0.tray.3.nozzle_temp_min":{"modify":"","name":"nozzle_temp_min","type":"string","role":"state","read":true,"write":false,"value":"190"},"00M09A371200669.ams.ams.0.tray.3.remain":{"modify":"","name":"remain","type":"number","role":"state","read":true,"write":false,"value":-1},"00M09A371200669.ams.ams.0.tray.3.tag_uid":{"modify":"","name":"tag_uid","type":"string","role":"state","read":true,"write":false,"value":"0000000000000000"},"00M09A371200669.ams.ams.0.tray.3.tray_color":{"modify":"","name":"tray_color","type":"string","role":"state","read":true,"write":false,"value":"898989FF"},"00M09A371200669.ams.ams.0.tray.3.tray_diameter":{"modify":"","name":"tray_diameter","type":"string","role":"state","read":true,"write":false,"value":"0.00"},"00M09A371200669.ams.ams.0.tray.3.tray_id_name":{"modify":"","name":"tray_id_name","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.3.tray_info_idx":{"modify":"","name":"tray_info_idx","type":"string","role":"state","read":true,"write":false,"value":"GFL99"},"00M09A371200669.ams.ams.0.tray.3.tray_sub_brands":{"modify":"","name":"tray_sub_brands","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.3.tray_type":{"modify":"","name":"tray_type","type":"string","role":"state","read":true,"write":false,"value":"PLA"},"00M09A371200669.ams.ams.0.tray.3.tray_uuid":{"modify":"","name":"tray_uuid","type":"string","role":"state","read":true,"write":false,"value":"00000000000000000000000000000000"},"00M09A371200669.ams.ams.0.tray.3.tray_weight":{"modify":"","name":"tray_weight","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.3.xcam_info":{"modify":"","name":"xcam_info","type":"string","role":"state","read":true,"write":false,"value":"000000000000000000000000"},"00M09A371200669.ams.version":{"modify":"","name":"version","type":"number","role":"state","read":true,"write":false,"value":2219},"00M09A371200669.ams.ams.0.tray.0.bed_temp":{"modify":["toNumber"],"name":"Bed Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":"0"},"00M09A371200669.ams.ams.0.tray.1.bed_temp":{"modify":["toNumber"],"name":"Bed Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":"0"},"00M09A371200669.ams.ams.0.tray.3.bed_temp":{"modify":["toNumber"],"name":"Bed Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":"0"},"00M09A371200669.bed_temper":{"modify":["toNumber"],"name":"Bed current Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":35},"00M09A371200669.gcode_state":{"modify":"","name":"gcode_state","type":"string","role":"state","read":true,"write":false,"value":"RUNNING"},"00M09A371200669.mc_print_stage":{"modify":"","name":"mc_print_stage","type":"string","role":"state","read":true,"write":false,"value":"2"},"00M09A371200669.ams_rfid_status":{"modify":"","name":"ams_rfid_status","type":"number","role":"state","read":true,"write":false,"value":2},"00M09A371200669.ipcam.timelapse":{"modify":"","name":"timelapse","type":"string","role":"state","read":true,"write":false,"value":"enable"},"00M09A371200669.ams.tray_exist_bits":{"modify":"","name":"tray_exist_bits","type":"string","role":"state","read":true,"write":false,"value":"f"},"00M09A371200669.ams.tray_is_bbl_bits":{"modify":"","name":"tray_is_bbl_bits","type":"string","role":"state","read":true,"write":false,"value":"f"},"00M09A371200669.ams.tray_read_done_bits":{"modify":"","name":"tray_read_done_bits","type":"string","role":"state","read":true,"write":false,"value":"f"},"00M09A371200669.ams.ams.0.tray.2.bed_temp_type":{"modify":"","name":"bed_temp_type","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.2.cali_idx":{"modify":"","name":"cali_idx","type":"number","role":"state","read":true,"write":false,"value":-1},"00M09A371200669.ams.ams.0.tray.2.cols":{"modify":"","name":"cols","type":"string","role":"state","read":true,"write":false,"value":"[\"F98C36FF\"]"},"00M09A371200669.ams.ams.0.tray.2.ctype":{"modify":"","name":"ctype","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.ams.ams.0.tray.2.drying_temp":{"modify":"","name":"drying_temp","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.2.drying_time":{"modify":"","name":"drying_time","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.2.nozzle_temp_max":{"modify":"","name":"nozzle_temp_max","type":"string","role":"state","read":true,"write":false,"value":"240"},"00M09A371200669.ams.ams.0.tray.2.nozzle_temp_min":{"modify":"","name":"nozzle_temp_min","type":"string","role":"state","read":true,"write":false,"value":"190"},"00M09A371200669.ams.ams.0.tray.2.remain":{"modify":"","name":"remain","type":"number","role":"state","read":true,"write":false,"value":-1},"00M09A371200669.ams.ams.0.tray.2.tag_uid":{"modify":"","name":"tag_uid","type":"string","role":"state","read":true,"write":false,"value":"0000000000000000"},"00M09A371200669.ams.ams.0.tray.2.tray_color":{"modify":"","name":"tray_color","type":"string","role":"state","read":true,"write":false,"value":"F98C36FF"},"00M09A371200669.ams.ams.0.tray.2.tray_diameter":{"modify":"","name":"tray_diameter","type":"string","role":"state","read":true,"write":false,"value":"0.00"},"00M09A371200669.ams.ams.0.tray.2.tray_id_name":{"modify":"","name":"tray_id_name","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.2.tray_info_idx":{"modify":"","name":"tray_info_idx","type":"string","role":"state","read":true,"write":false,"value":"GFL99"},"00M09A371200669.ams.ams.0.tray.2.tray_sub_brands":{"modify":"","name":"tray_sub_brands","type":"string","role":"state","read":true,"write":false,"value":""},"00M09A371200669.ams.ams.0.tray.2.tray_type":{"modify":"","name":"tray_type","type":"string","role":"state","read":true,"write":false,"value":"PLA"},"00M09A371200669.ams.ams.0.tray.2.tray_uuid":{"modify":"","name":"tray_uuid","type":"string","role":"state","read":true,"write":false,"value":"00000000000000000000000000000000"},"00M09A371200669.ams.ams.0.tray.2.tray_weight":{"modify":"","name":"tray_weight","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.ams.ams.0.tray.2.xcam_info":{"modify":"","name":"xcam_info","type":"string","role":"state","read":true,"write":false,"value":"000000000000000000000000"},"00M09A371200669.filam_bak":{"modify":"","name":"filam_bak","type":"string","role":"state","read":true,"write":false,"value":"[2]"},"00M09A371200669.ams.ams.0.tray.2.bed_temp":{"modify":["toNumber"],"name":"Bed Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":"0"},"00M09A371200669.ams.tray_reading_bits":{"modify":"","name":"tray_reading_bits","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.gcode_file_prepare_percent":{"modify":"","name":"gcode_file_prepare_percent","type":"string","role":"state","read":true,"write":false,"value":"100"},"00M09A371200669.gcode_start_time":{"modify":"","name":"gcode_start_time","type":"string","role":"state","read":true,"write":false,"value":"1697966441"},"00M09A371200669.profile_id":{"modify":"","name":"profile_id","type":"string","role":"state","read":true,"write":false,"value":"23195437"},"00M09A371200669.subtask_id":{"modify":"","name":"subtask_id","type":"string","role":"state","read":true,"write":false,"value":"44801679"},"00M09A371200669.subtask_name":{"modify":"","name":"subtask_name","type":"string","role":"state","read":true,"write":false,"value":"Rear-Right"},"00M09A371200669.task_id":{"modify":"","name":"task_id","type":"string","role":"state","read":true,"write":false,"value":"44801678"},"00M09A371200669.gcode_start_timeFormatted":{"modify":"","name":"gcode_start_timeFormatted","type":"string","role":"state","read":true,"write":false,"value":"Sun Oct 22 2023 11:20:41 GMT+0200 (Mitteleuropäische Sommerzeit)"},"00M09A371200669.project_id":{"modify":"","name":"project_id","type":"string","role":"state","read":true,"write":false,"value":"23259646"},"00M09A371200669.stg":{"modify":"","name":"stg","type":"string","role":"state","read":true,"write":false,"value":"[2,14,1,8]"},"00M09A371200669.total_layer_num":{"modify":"","name":"total_layer_num","type":"number","role":"state","read":true,"write":false,"value":1224},"00M09A371200669.hms.0.attr":{"modify":"","name":"attr","type":"number","role":"state","read":true,"write":false,"value":117449216},"00M09A371200669.hms.0.code":{"modify":"","name":"code","type":"number","role":"state","read":true,"write":false,"value":196610},"00M09A371200669.hms.1.attr":{"modify":"","name":"attr","type":"number","role":"state","read":true,"write":false,"value":201327360},"00M09A371200669.hms.1.code":{"modify":"","name":"code","type":"number","role":"state","read":true,"write":false,"value":196619},"00M09A371200669.mc_print_error_code":{"modify":"","name":"mc_print_error_code","type":"string","role":"state","read":true,"write":false,"value":"0"},"00M09A371200669.print_error":{"modify":"","name":"print_error","type":"number","role":"state","read":true,"write":false,"value":0},"00M09A371200669.fail_reason":{"modify":"","name":"fail_reason","type":"string","role":"state","read":true,"write":false,"value":"0"}}`
