### ISSUE TITLE
Cannot set properties of undefined "Spd_lvl"

### ISSUE THREAD

**Issue by coyote1** [DrozmotiX/ioBroker.bambulab#38]
Adapter Version 0.2.0

Drucker: P1S mit AMS

Fehler:

`
bambulab.0 | 2023-10-19 18:43:32.446 | error | [messageHandler] TypeError: Cannot set properties of undefined (setting 'spd_lvl') \| TypeError: Cannot set properties of undefined (setting 'spd_lvl') at Bambulab.messageHandler (/opt/iobroker/node_modules/iobroker.bambulab/main.js:181:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.bambulab/main.js:107:11) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/publish.js:97:20) at handle (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/index.js:28:35) at work (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:227:40) at writable._write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:252:13) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) at Writable.write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
-- | -- | -- | --
`

**Comment by darkdevil373** [comment]
den gleichen Fehler bekomme ich auch alle 5 Sekunden.

P1P mit AMS

**Comment by DutchmanNL** [comment]
ich benötige mal eure log daten :), bitte adapter auf debug stellen. Dan sollte 2 Meldungen kommen befohr der Fehler auftritt:

- Printer Message 
- Response of JSONexploer

dahinter steht einen JSON mit der Drucker Nachricht, könnt ihr die mal bitte hier posten ?

**Comment by darkdevil373** [comment]
Printer Message:

`Printer Message {"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":16.96875,"nozzle_target_temper":0,"bed_temper":15.6875,"bed_target_temper":0,"chamber_temper":5,"mc_print_stage":"1","heatbreak_fan_speed":"0","cooling_fan_speed":"0","big_fan1_speed":"0","big_fan2_speed":"0","mc_percent":0,"mc_remaining_time":0,"ams_status":0,"ams_rfid_status":0,"hw_switch_state":0,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-58dBm","gcode_state":"IDLE","gcode_file_prepare_percent":"0","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"0","profile_id":"0","task_id":"0","subtask_id":"0","subtask_name":"","gcode_file":"","stg":[],"stg_cur":0,"print_type":"idle","home_flag":16776,"mc_print_line_number":"0","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":0,"total_layer_num":0,"hms":[],"online":{"ahb":false,"rfid":false,"version":1601781414},"ams":{"ams":[{"id":"0","humidity":"2","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.019999999552965164,"n":1.399999976158142,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFL96","tray_type":"PLA","tray_sub_brands":"","tray_color":"F95D73FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"240","nozzle_temp_min":"190","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.019999999552965164,"n":1.399999976158142,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFL99","tray_type":"PLA","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"240","nozzle_temp_min":"190","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"2","remain":-1,"k":0.019999999552965164,"n":1.399999976158142,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG98","tray_type":"PETG-CF","tray_sub_brands":"","tray_color":"000000FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"240","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"3","remain":85,"k":0.019999999552965164,"n":1.399999976158142,"tag_uid":"FD06B7C000000100","tray_id_name":"A50-K0","tray_info_idx":"GFA50","tray_type":"PLA-CF","tray_sub_brands":"PLA-CF","tray_color":"000000FF","tray_weight":"1000","tray_diameter":"1.75","tray_temp":"55","tray_time":"8","bed_temp_type":"1","bed_temp":"35","nozzle_temp_max":"240","nozzle_temp_min":"200","xcam_info":"803E803EE803E8030000403F","tray_uuid":"351023BB6E464F4BBC0DD97626895608"}]}],"ams_exist_bits":"1","tray_exist_bits":"f","tray_is_bbl_bits":"f","tray_tar":"255","tray_now":"255","tray_pre":"255","tray_read_done_bits":"f","tray_reading_bits":"0","version":7,"insert_flag":true,"power_on_flag":false},"ipcam":{"ipcam_dev":"1","ipcam_record":"enable","timelapse":"disable","mode_bits":3},"vt_tray":{"id":"254","tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"","tray_type":"","tray_sub_brands":"","tray_color":"00000000","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"0","nozzle_temp_min":"0","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000","remain":0,"k":0.019999999552965164,"n":1.399999976158142},"lights_report":[{"node":"chamber_light","mode":"off"}],"upgrade_state":{"sequence_id":0,"progress":"","status":"","consistency_request":false,"dis_state":1,"err_code":0,"force_upgrade":false,"message":"","module":"","new_version_state":1,"new_ver_list":[{"name":"ota","cur_ver":"01.04.00.00","new_ver":"01.04.01.00"},{"name":"ams/0","cur_ver":"00.00.06.32","new_ver":"00.00.06.40"}]},"command":"push_status","msg":0,"sequence_id":"32"}}`

Response of JSONexploer:

`Response of JSONexploer: {}`

Etwas später tauchen dann wieder Einträge von Response of JSONexplorer auf:

`Response of JSONexploer: {"Seriennummer.wifi_signal":{"modify":"","name":"wifi_signal","type":"string","role":"state","read":true,"write":false,"value":"-56dBm"},"Seriennummer.command":{"modify":"","name":"command","type":"string","role":"state","read":true,"write":false,"value":"push_status"},"Seriennummer.msg":{"modify":"","name":"msg","type":"number","role":"state","read":true,"write":false,"value":1},"Seriennummer.sequence_id":{"modify":"","name":"sequence_id","type":"string","role":"state","read":true,"write":false,"value":"36"},"Seriennummer.hms.hmsErrorCount":{"modify":"","name":"hmsErrorCount","type":"number","role":"state","read":true,"write":false,"value":0},"Seriennummer.hms.hmsErrors":{"modify":"","name":"hmsErrors","type":"boolean","role":"state","read":true,"write":false,"value":false}}`

**Comment by DutchmanNL** [comment]
hmm der Fehler tritt hier auf : https://github.com/DrozmotiX/ioBroker.bambulab/blob/main/main.js#L179-L182
was aber durch diesen code hier eigentlich nicht sein kan : https://github.com/DrozmotiX/ioBroker.bambulab/blob/main/main.js#L158

Die JSON sieht auch OK aus

es sieht so aus also alter code ausgeführt wird, könntest du zu Sicherheit den adapter mal neu installieren ?
ich kan es nicht reproduzieren :/

**Comment by DutchmanNL** [comment]
@darkdevil373 in dem JSON beispiel ist der wert drin der den Fehler versucht, kan es sein das bei dieser nachreicht keine Fehlermeldung auftrat ?

ich brauchte dan einen JSON vor dem Fehler um raus zu finden ob es daran liegt das er fehlt. Ich oruefe eigentlich darauf also sollte es passen aber man weis ja nie

**Comment by darkdevil373** [comment]
@DutchmanNL: Ich habe den Adapter gerade einmal komplett gelöscht und von GitHub neu installiert. 
Als Drucker habe ich den P1P gewählt und die Seriennummer und IP Adresse, sowie den Access Code einegtragen.
Der Fehler:

`<html>
<body>


[messageHandler] TypeError: Cannot set properties of undefined (setting 'spd_lvl') \| TypeError: Cannot set properties of undefined (setting 'spd_lvl') at Bambulab.messageHandler (/opt/iobroker/node_modules/iobroker.bambulab/main.js:181:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.bambulab/main.js:107:11) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/publish.js:97:20) at handle (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/index.js:28:35) at work (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:227:40) at writable._write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:252:13) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) at Writable.write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
--
 

<br class="Apple-interchange-newline">
</body>
</html>

bleibt allerdings. Des Weiteren habe ich nun deutlich weniger Datenpunkte als vorher....`

**Comment by coyote1** [comment]
Bei mir leider auch, gleicher Fehler auch während dem Drucken. Habe auch mal auf X1 umgestellt, Fehler bleibt.

**Comment by DutchmanNL** [comment]
> Bei mir leider auch, gleicher Fehler auch während dem Drucken. Habe auch mal auf X1 umgestellt, Fehler bleibt. 

Zum Mäuse melken, bin leider krank geworden diese Woche aber werde heute auch bei mir mal nen Druck starten mit dem XC1 es muss doch reproduzierbar sein 😒

Das Problem war sowohl bei dem P1 als den X1 Modellen Right ?

**Comment by coyote1** [comment]
Also ich hab den P1S, habe nur den Adapter mal zum Test auf X1 gestellt. 
Momentan läuft ein Druck, seltsam ist, dass der Fehler seit 17 min nicht mehr aufgetreten ist. 
Ich beobachte weiter. Wenn du was an Log brauchst sag Bescheid

**Comment by DutchmanNL** [comment]
> Also ich hab den P1S, habe nur den Adapter mal zum Test auf X1 gestellt. 
> Momentan läuft ein Druck, seltsam ist, dass der Fehler seit 17 min nicht mehr aufgetreten ist. 
> Ich beobachte weiter. Wenn du was an Log brauchst sag Bescheid

Ich bräuchte vor allem das log im Moment wo der Fehler auftritt, kan es mir echt nicht erklären gerade 🤒

**Comment by coyote1** [comment]
Ich kann es leider auch nicht ganz nachvollziehen, wann der Fehler auftaucht. Meiner Meinung einfach sporadisch, also nicht bei Druckstart, Druckende oder Leerlauf. Hier nochmal ein Debug, während eines Drucks.

`<html>
<body>


bambulab.0 | 2023-10-22 15:44:22.311 | debug | Printer Message {"print":{"nozzle_temper":219.65625,"bed_temper":55,"big_fan1_speed":"12","wifi_signal":"-63dBm","mc_print_line_number":"36032","fan_gear":9882879,"command":"push_status","msg":1,"sequence_id":"2497"}}
-- | -- | -- | --
bambulab.0 | 2023-10-22 15:44:20.277 | error | [messageHandler] TypeError: Cannot set properties of undefined (setting 'spd_lvl') \| TypeError: Cannot set properties of undefined (setting 'spd_lvl') at Bambulab.messageHandler (/opt/iobroker/node_modules/iobroker.bambulab/main.js:181:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.bambulab/main.js:107:11) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/publish.js:97:20) at handle (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/index.js:28:35) at work (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:227:40) at writable._write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:252:13) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) at Writable.write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
bambulab.0 | 2023-10-22 15:44:20.277 | debug | Printer Message {"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":219.59375,"nozzle_target_temper":220,"bed_temper":55.03125,"bed_target_temper":55,"chamber_temper":5,"mc_print_stage":"2","heatbreak_fan_speed":"15","cooling_fan_speed":"15","big_fan1_speed":"11","big_fan2_speed":"8","mc_percent":16,"mc_remaining_time":136,"ams_status":768,"ams_rfid_status":2,"hw_switch_state":1,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-60dBm","gcode_state":"RUNNING","gcode_file_prepare_percent":"100","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"23285933","profile_id":"23221409","task_id":"44852852","subtask_id":"44852853","subtask_name":"Poop_Chute_magnetic","gcode_file":"Poop_Chute_magnetic.3mf","stg":[2,14,13],"stg_cur":0,"print_type":"cloud","home_flag":16687,"mc_print_line_number":"35959","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":33,"total_layer_num":1075,"fan_gear":9876223,"hms":[],"online":{"ahb":false,"rfid":false,"version":1357057627},"ams":{"ams":[{"id":"0","humidity":"4","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.019999999552965164,"n":1,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFA00","tray_type":"PLA","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"240","nozzle_temp_min":"190","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.019999999552965164,"n":1.399999976158142,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFA00","tray_type":"PLA","tray_sub_brands":"","tray_color":"DDB1D4FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"240","nozzle_temp_min":"190","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"2","remain":-1,"k":0.019999999552965164,"n":1,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFB00","tray_type":"ABS","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"280","nozzle_temp_min":"240","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"3"}]}],"ams_exist_bits":"1","tray_exist_bits":"7","tray_is_bbl_bits":"7","tray_tar":"0","tray_now":"0","tray_pre":"0","tray_read_done_bits":"7","tray_reading_bits":"0","version":33,"insert_flag":true,"power_on_flag":true},"ipcam":{"ipcam_dev":"1","ipcam_record":"enable","timelapse":"disable","mode_bits":3},"vt_tray":{"id":"254","tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"","tray_type":"","tray_sub_brands":"","tray_color":"00000000","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"0","nozzle_temp_min":"0","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000","remain":0,"k":0.019999999552965164,"n":1},"lights_report":[{"node":"chamber_light","mode":"on"}],"upgrade_state":{"sequence_id":0,"progress":"","status":"","consistency_request":false,"dis_state":0,"err_code":0,"force_upgrade":false,"message":"","module":"","new_version_state":2,"new_ver_list":[]},"command":"push_status","msg":0,"sequence_id":"2496"}}


</body>
</html>`

**Comment by coyote1** [comment]
Kommando zurück, das war nur weil ich noch den Adapter auf X1 Printer stehen hatte. Stelle ich auf P1S um, kommt der Fehler alle 5 Sekunden, also so wie das Polling eingestellt ist

`<html>
<body>


bambulab.0 | 2023-10-22 15:57:47.619 | error | [messageHandler] TypeError: Cannot set properties of undefined (setting 'spd_lvl') \| TypeError: Cannot set properties of undefined (setting 'spd_lvl') at Bambulab.messageHandler (/opt/iobroker/node_modules/iobroker.bambulab/main.js:181:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.bambulab/main.js:107:11) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/publish.js:97:20) at handle (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/index.js:28:35) at work (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:227:40) at writable._write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:252:13) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) at Writable.write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
-- | -- | -- | --
bambulab.0 | 2023-10-22 15:57:47.619 | debug | Printer Message {"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":220.09375,"nozzle_target_temper":220,"bed_temper":55,"bed_target_temper":55,"chamber_temper":5,"mc_print_stage":"2","heatbreak_fan_speed":"15","cooling_fan_speed":"15","big_fan1_speed":"11","big_fan2_speed":"8","mc_percent":24,"mc_remaining_time":123,"ams_status":768,"ams_rfid_status":2,"hw_switch_state":1,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-58dBm","gcode_state":"RUNNING","gcode_file_prepare_percent":"100","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"23285933","profile_id":"23221409","task_id":"44852852","subtask_id":"44852853","subtask_name":"Poop_Chute_magnetic","gcode_file":"Poop_Chute_magnetic.3mf","stg":[2,14,13],"stg_cur":0,"print_type":"cloud","home_flag":16687,"mc_print_line_number":"65744","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":90,"total_layer_num":1075,"fan_gear":9876223,"hms":[],"online":{"ahb":false,"rfid":false,"version":1357057627},"ams":{"ams":[{"id":"0","humidity":"4","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.019999999552965164,"n":1,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFA00","tray_type":"PLA","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"240","nozzle_temp_min":"190","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.019999999552965164,"n":1.399999976158142,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFA00","tray_type":"PLA","tray_sub_brands":"","tray_color":"DDB1D4FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"240","nozzle_temp_min":"190","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"2","remain":-1,"k":0.019999999552965164,"n":1,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFB00","tray_type":"ABS","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"280","nozzle_temp_min":"240","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"3"}]}],"ams_exist_bits":"1","tray_exist_bits":"7","tray_is_bbl_bits":"7","tray_tar":"0","tray_now":"0","tray_pre":"0","tray_read_done_bits":"7","tray_reading_bits":"0","version":33,"insert_flag":true,"power_on_flag":true},"ipcam":{"ipcam_dev":"1","ipcam_record":"enable","timelapse":"disable","mode_bits":3},"vt_tray":{"id":"254","tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"","tray_type":"","tray_sub_brands":"","tray_color":"00000000","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"0","nozzle_temp_min":"0","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000","remain":0,"k":0.019999999552965164,"n":1},"lights_report":[{"node":"chamber_light","mode":"on"}],"upgrade_state":{"sequence_id":0,"progress":"","status":"","consistency_request":false,"dis_state":0,"err_code":0,"force_upgrade":false,"message":"","module":"","new_version_state":2,"new_ver_list":[]},"command":"push_status","msg":0,"sequence_id":"2790"}}
bambulab.0 | 2023-10-22 15:57:46.695 | debug | Publish message {"pushing":{"sequence_id":"1","command":"pushall"},"user_id":"1234567890"}
bambulab.0 | 2023-10-22 15:57:44.648 | debug | Response of JSONexploer: {"01P00A382500731.wifi_signal":{"modify":"","name":"wifi_signal","type":"string","role":"state","read":true,"write":false,"value":"-60dBm"},"01P00A382500731.command":{"modify":"","name":"command","type":"string","role":"state","read":true,"write":false,"value":"push_status"},"01P00A382500731.msg":{"modify":"","name":"msg","type":"number","role":"state","read":true,"write":false,"value":1},"01P00A382500731.sequence_id":{"modify":"","name":"sequence_id","type":"string","role":"state","read":true,"write":false,"value":"2789"},"01P00A382500731.nozzle_temper":{"modify":["toNumber"],"name":"Nozzle current Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":220},"01P00A382500731.bed_temper":{"modify":["toNumber"],"name":"Bed current Temperature","type":"number","role":"value.temperature","read":true,"write":false,"unit":"°C","value":55},"01P00A382500731.mc_print_line_number":{"modify":["toNumber"],"name":"Printjob line number","type":"number","role":"state","read":true,"write":false,"value":65685},"01P00A382500731.hms.hmsErrorCount":{"modify":"","name":"hmsErrorCount","type":"number","role":"state","read":true,"write":false,"value":0},"01P00A382500731.hms.hmsErrors":{"modify":"","name":"hmsErrors","type":"boolean","role":"state","read":true,"write":false,"value":false},"01P00A382500731.layer_num":{"modify":"","name":"layer_num","type":"number","role":"state","read":true,"write":false,"value":89},"01P00A382500731.fan_gear":{"modify":"","name":"fan_gear","type":"number","role":"state","read":true,"write":false,"value":9882623},"01P00A382500731.big_fan1_speed":{"modify":["toNumber"],"name":"AUX Fan 1 Speed","type":"number","role":"level","read":true,"write":true,"unit":"%","value":80},"01P00A382500731.control.big_fan1_speed":{"modify":["toNumber"],"name":"AUX Fan 1 Speed","type":"number","role":"level","read":true,"write":true,"unit":"%","value":80},"01P00A382500731.mc_remaining_time":{"modify":"","name":"Remaining Time","type":"string","role":"value.time","read":true,"write":false,"value":"02:03"}}
bambulab.0 | 2023-10-22 15:57:44.554 | debug | Printer Message {"print":{"nozzle_temper":220,"big_fan1_speed":"11","mc_print_line_number":"65685","fan_gear":9882623,"command":"push_status","msg":1,"sequence_id":"2789"}}
bambulab.0 | 2023-10-22 15:57:42.539 | error | [messageHandler] TypeError: Cannot set properties of undefined (setting 'spd_lvl') \| TypeError: Cannot set properties of undefined (setting 'spd_lvl') at Bambulab.messageHandler (/opt/iobroker/node_modules/iobroker.bambulab/main.js:181:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.bambulab/main.js:107:11) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/publish.js:97:20) at handle (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/handlers/index.js:28:35) at work (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:227:40) at writable._write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/mqtt/build/lib/client.js:252:13) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) at Writable.write (/opt/iobroker/node_modules/iobroker.bambulab/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)


</body>
</html>`
