### ISSUE TITLE
Warnings und Error

### ISSUE THREAD

**Issue by Apropo1710** [DrozmotiX/ioBroker.bambulab#39]
Bei meinem X1C kommen im Log ständig folgende Fehler. Die Warnings mit dem Sentry nur beim Start

<html>
<body>

bambulab.0 | 2023-10-20 16:20:22.601 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A320700469","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00301C313009102","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00201A2C3004411","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A2C0506995","sw_ver":"00.00.06.40"}],"sequence_id":"2018"}}
-- | -- | -- | --
bambulab.0 | 2023-10-20 16:20:21.495 | error | Unknown Message {"liveview":{"authkey":"mbjuc4fr","command":"prepare","passwd":"rcq5nc","reason":"already started","result":"succeed","sequence_id":"0","ttcode":"C4NBX239HZPYUP2N111A"}}
bambulab.0 | 2023-10-20 16:19:08.948 | info | State value to set for "bambulab.0.00M09A320700469.ams.ams.0.tray.3.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-10-20 16:19:08.850 | info | State value to set for "bambulab.0.00M09A320700469.ams.ams.0.tray.2.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-10-20 16:19:08.820 | info | State value to set for "bambulab.0.00M09A320700469.ams.ams.0.tray.1.bed_temp" has to be type "number" but received type "string"
bambulab.0 | 2023-10-20 16:19:07.742 | warn | Sentry disabled, error catched: State attribute definition missing for 'version' with value '218' and type of value 'number'
bambulab.0 | 2023-10-20 16:19:07.689 | warn | Sentry disabled, error catched: State attribute definition missing for 'xcam_info' with value '34218813F401E8030000003F' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.687 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_weight' with value '1000' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.684 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_uuid' with value '2BCB8A49B1CC4FF7A7C202168FC69D71' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.682 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_type' with value 'PLA' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.679 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_sub_brands' with value 'PLA Basic' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.676 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_info_idx' with value 'GFA00' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.674 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_id_name' with value 'A00-W1' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.671 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_diameter' with value '1.75' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.666 | warn | Sentry disabled, error catched: State attribute definition missing for 'tray_color' with value 'FFFFFFFF' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.664 | warn | Sentry disabled, error catched: State attribute definition missing for 'tag_uid' with value '1DCC262100000100' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.661 | warn | Sentry disabled, error catched: State attribute definition missing for 'remain' with value '-4' and type of value 'number'
bambulab.0 | 2023-10-20 16:19:07.658 | warn | Sentry disabled, error catched: State attribute definition missing for 'nozzle_temp_min' with value '190' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.656 | warn | Sentry disabled, error catched: State attribute definition missing for 'nozzle_temp_max' with value '230' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.653 | warn | Sentry disabled, error catched: State attribute definition missing for 'drying_time' with value '8' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.650 | warn | Sentry disabled, error catched: State attribute definition missing for 'drying_temp' with value '55' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.647 | warn | Sentry disabled, error catched: State attribute definition missing for 'ctype' with value '0' and type of value 'number'
bambulab.0 | 2023-10-20 16:19:07.645 | warn | Sentry disabled, error catched: State attribute definition missing for 'cols' with value '["FFFFFFFF"]' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.642 | warn | Sentry disabled, error catched: State attribute definition missing for 'cali_idx' with value '6583' and type of value 'number'
bambulab.0 | 2023-10-20 16:19:07.639 | warn | Sentry disabled, error catched: State attribute definition missing for 'bed_temp_type' with value '1' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.635 | warn | Sentry disabled, error catched: State attribute definition missing for 'temp' with value '28.6' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.632 | warn | Sentry disabled, error catched: State attribute definition missing for 'id' with value '0' and type of value 'string'
bambulab.0 | 2023-10-20 16:19:07.629 | warn | Sentry disabled, error catched: State attribute definition missing for 'humidity' with value '3' and type of value 'string'
bambulab.0 | 2023-10-20 16:18:24.164 | warn | Sentry disabled, error catched: State attribute definition missing for 'wifi_signal' with value '-47dBm' and type of value 'string'
bambulab.0 | 2023-10-20 16:17:27.918 | warn | Sentry disabled, error catched: State attribute definition missing for 'hmsErrors' with value 'false' and type of value 'boolean'
bambulab.0 | 2023-10-20 16:17:27.900 | warn | Sentry disabled, error catched: State attribute definition missing for 'hmsErrorCount' with value '0' and type of value 'number'
bambulab.0 | 2023-10-20 16:17:27.896 | warn | Sentry disabled, error catched: State attribute definition missing for 't_utc' with value '1697811447565' and type of value 'number'
bambulab.0 | 2023-10-20 16:17:27.891 | warn | Sentry disabled, error catched: State attribute definition missing for 'sequence_id' with value '2614' and type of value 'string'
bambulab.0 | 2023-10-20 16:17:27.885 | warn | Sentry disabled, error catched: State attribute definition missing for 'msg' with value '1' and type of value 'number'
bambulab.0 | 2023-10-20 16:17:27.867 | warn | Sentry disabled, error catched: State attribute definition missing for 'command' with value 'push_status' and type of value 'string'
bambulab.0 | 2023-10-20 16:17:24.282 | info | Printer connected

</body>
</html>

**Comment by Matzebhv** [comment]
Die Errors habe ich tatsächlich nicht, allerdings die Warnings beim Druckstart. Ebenfalls X1C

**Comment by DutchmanNL** [comment]
> Die Errors habe ich tatsächlich nicht, allerdings die Warnings beim Druckstart. Ebenfalls X1C

ah ok bei nem druck start passiert das, da gibt es wohl ein par neue werte muss ich einbinden

**Comment by Matzebhv** [comment]
Heute Morgen hatte ich die Fehlermeldungen beim Start eines Druckes ebenfalls:

`<html>
<body>


bambulab.0 | 2023-10-22 11:20:43.524 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20013"}}
-- | -- | -- | --
bambulab.0 | 2023-10-22 11:20:27.603 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20011"}}
host.iOBroker | 2023-10-22 11:20:02.896 | info | instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
dwd.0 | 2023-10-22 11:20:02.378 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
dwd.0 | 2023-10-22 11:20:01.983 | info | starting. Version 2.8.5 in /opt/iobroker/node_modules/iobroker.dwd, node: v18.18.1, js-controller: 5.0.14
host.iOBroker | 2023-10-22 11:20:00.154 | info | instance system.adapter.dwd.0 started with pid 2974141
bambulab.0 | 2023-10-22 11:15:17.342 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20010"}}
host.iOBroker | 2023-10-22 11:15:15.993 | info | instance system.adapter.daswetter.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
daswetter.0 | 2023-10-22 11:15:15.978 | info | cleaned everything up...
daswetter.0 | 2023-10-22 11:15:15.474 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): All data handled, adapter stopped until next scheduled moment
bambulab.0 | 2023-10-22 11:15:14.822 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20008"}}
bambulab.0 | 2023-10-22 11:15:14.726 | error | Unknown Message {"liveview":{"authkey":"xxxxx","command":"prepare","passwd":"xxxxx","result":"succeed","sequence_id":"0","ttcode":"C2G8R5FP2ZLN1346111A"}}
bambulab.0 | 2023-10-22 11:15:14.323 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20006"}}
bambulab.0 | 2023-10-22 11:15:14.025 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20005"}}
bambulab.0 | 2023-10-22 11:15:14.024 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20003"}}
bambulab.0 | 2023-10-22 11:15:14.018 | error | Unknown Message {"info":{"command":"get_version","module":[{"hw_ver":"","name":"ota","sn":"","sw_ver":"01.06.05.01"},{"hw_ver":"AP05","name":"rv1126","sn":"00M09A371200669","sw_ver":"00.00.24.13"},{"hw_ver":"TH09","name":"th","sn":"00306D361407108","sw_ver":"00.00.05.83"},{"hw_ver":"MC07","name":"mc","sn":"00206A352400064","sw_ver":"00.00.16.68/00.00.16.68"},{"hw_ver":"","name":"xm","sn":"","sw_ver":"00.01.02.02"},{"hw_ver":"AMS08","name":"ams/0","sn":"00600A371205703","sw_ver":"00.00.06.40"}],"sequence_id":"20001"}}


</body>
</html>`
