### ISSUE TITLE
Keine Daten

### ISSUE THREAD

**Issue by darkdevil373** [DrozmotiX/ioBroker.bambulab#5]
Ich habe den Adapter soeben installiert und die Daten meines P1Ps eingetragen.

 Außer der Datenpunkte chamberlight, resume, start und pause sehe ich keine weiteren Daten (zB Temperaturen, oder Fortschritte) 

Des Weiteren tauchen im log im Sekunden Takt Meldungen "Printer connected" auf

**Comment by DutchmanNL** [comment]
> Ich habe den Adapter soeben installiert und die Daten meines P1Ps eingetragen.
> 
> Außer der Datenpunkte chamberlight, resume, start und pause sehe ich keine weiteren Daten (zB Temperaturen, oder Fortschritte)
> 
> Des Weiteren tauchen im log im Sekunden Takt Meldungen "Printer connected" auf

hmm, ich habe leider keine P1 die matt api sollte aber dieselbe sein. Seriennummer hast du eingegeben ?

**Comment by darkdevil373** [comment]
Ja habe ich, die Buttons funktionieren auch 👍

**Comment by DutchmanNL** [comment]
Firmware des Drucker auf aktuellsten stand ?

**Comment by darkdevil373** [comment]
Ja, up to date

**Comment by DutchmanNL** [comment]
probiere es mal bitte mit der version V.0.1.1, ich habe hier das logging etwas erweitert.
Bitte den adapter auf debug stellen und die LOG ausgabe hier teilen. Am besten das log herunterladen und alles bezüglich dieses adapters hier posten (also nicht copy/paste aus dem admin heraus)

ich möchte mal schauen wie und was für den bei dir ankommen eventuell muss ich fuer den P1 noch etwas anderes umplementieren

**Comment by darkdevil373** [comment]
[iobroker.2023-07-26.log](https://github.com/DrozmotiX/ioBroker.bambulab/files/12173777/iobroker.2023-07-26.log)

so schaut der log aus.

**Comment by darkdevil373** [comment]
Das ist alles. Ich habe gerade den Adapter auf alles und debug gestellt, das aus dem log sein die Einträge die ich im Protokoll bekomme

**Comment by DutchmanNL** [comment]
> Das ist alles. Ich habe gerade den Adapter auf alles und debug gestellt, das aus dem log sein die Einträge die ich im Protokoll bekomme

ich sehe im log aber keine debug information, es sollte mindestens diese Zeile kommen :)
```
this.log.debug(`Try to connect to printer`);
```

bist du dir sicher das das log-level des Adapter auf debug steht ?
![Screenshot 2023-07-26 at 17 05 04](https://github.com/DrozmotiX/ioBroker.bambulab/assets/7318445/a1582d0b-85c7-4f2e-9e45-02bf88a61e30)

**Comment by darkdevil373** [comment]
[logs - iobroker.txt](https://github.com/DrozmotiX/ioBroker.bambulab/files/12176203/logs.-.iobroker.txt)
schaut für mich immer noch gleich aus.

**Comment by DutchmanNL** [comment]
Da kommt schon etwas mehr, er acheint Probleme mit der Seriennummer zu haben wegen eines Spezialen karakters. 

Gibt die mal bitte neu ein in den Settings

**Comment by darkdevil373** [comment]
[iobroker.current.log](https://github.com/DrozmotiX/ioBroker.bambulab/files/12181379/iobroker.current.log)
Tatsächlich hat sich die Seriennummer überschrieben, das Ergebnis bleibt aber ähnlich.

**Comment by DutchmanNL** [comment]
> [iobroker.current.log](https://github.com/DrozmotiX/ioBroker.bambulab/files/12181379/iobroker.current.log)
> Tatsächlich hat sich die Seriennummer überschrieben, das Ergebnis bleibt aber ähnlich.

es sieht so aus also auf dem topic wo ich Daten erwarte nichts ankommt, werde mal recherchieren ob es da noch andere Optionen gibt.
Hattst du es eventuell vorher mal mit dem node-red flow probiert ? Ich kann mir gerade nicht erklären warum nichts ankommt

**Comment by DutchmanNL** [comment]
ok habe es gefunden, laut diesem forum post muss man einen Befehl schicken fuer den P1p damit er die Daten schickt.
Ich werde das implementieren und melden mich sobald eine neue version da ist.

Denke mal innerhalb der niesten 2 stunden

**Comment by DutchmanNL** [comment]
@darkdevil373  ok ich habe den Befehl jetzt so eingebaut das er bei einer connection einmalig ausgeführt wird, probiere es mal bitte mit der version 0.1.2

Ich muss dan verstehen ob werte ankommen, und ob dies nur einmalig ist oder danach permanent (bitte log wieder teilen :))
dan weis ich auch wie es integriert werden muss, einmaliger Befehl oder alles X Sekunden anfragen

**Comment by darkdevil373** [comment]
Nach dem Update schaut der log wie folgt aus.
Weitere Datenpunkte gibt es immer noch nicht. 
[iobroker.current.log](https://github.com/DrozmotiX/ioBroker.bambulab/files/12183746/iobroker.current.log)

**Comment by DutchmanNL** [comment]
pff schwierig so, ich schaue weiter.... da ich keinen p1p habe ist es try & error wen ich mal per Protest freigäbe drauf dürfte .... könnte das einiges einfacher machen :)

Washer das eventuell eine option um den port mal fuer ein par stunden fuer mich zu öffnen damit ich remote schauen kann was wir machen können ?

**Comment by DutchmanNL** [comment]
solved in current git version, will update to version 0.1.4 with proper quality, for testing it can be already used

thank you @darkdevil373 for you time !
