### ISSUE TITLE
P1P keine Werte + Dauerhafte Fehlermeldungen

### ISSUE THREAD

**Issue by Dommi239** [DrozmotiX/ioBroker.bambulab#54]
Ich habe die neuste Version installiert (v.0.3.0) und es werden keine Werte von dem Drucker ausgelesen und es werden dauerhafte folgende Fehler eingetragen:

![image](https://github.com/DrozmotiX/ioBroker.bambulab/assets/98487441/8f33d2e2-7e39-4c67-887e-fc5b166f55ee)

Es handelt sich um einen P1P.

**Comment by DutchmanNL** [comment]
> Ich habe die neuste Version installiert (v.0.3.0) und es werden keine Werte von dem Drucker ausgelesen und es werden dauerhafte folgende Fehler eingetragen:
> 
> 
> 
> ![image](https://github.com/DrozmotiX/ioBroker.bambulab/assets/98487441/8f33d2e2-7e39-4c67-887e-fc5b166f55ee)
> 
> 
> 
> Es handelt sich um einen P1P.

Bitte Adapter komplett löschen und neu installieren
Das liegt an einer Abhängigkeit die sich wohl leider bichtvuodated wen man die neue Version installiert

Wir hatten gestern bei jemand genaus dasselbe und damit war es gelöst

**Comment by Dommi239** [comment]
Super! Das hat geholfen. Vielen Dank für die schnelle Hilfe.
