### ISSUE TITLE
.finishTime" has to be type "date" but received type "string" 

### ISSUE THREAD

**Issue by skvarel** [DrozmotiX/ioBroker.bambulab#58]
![image](https://github.com/DrozmotiX/ioBroker.bambulab/assets/1114419/8a0a78a0-9c5e-4790-93aa-cf3100017638)

**Comment by DutchmanNL** [comment]
sometimes these type frustrate me, format of the value is correctly but as its a JSON somehow conversion to sting takes place.
will have a look

**Comment by SidM01** [comment]
Good evening!
I wanted to carefully ask whether a solution is already being worked on? Changing it manually to string isn't a problem, but if I restart again, the type is reset again and my log explodes.
I have an X1C.

In addition to the finish.Time there is also the message at nozzle.0.temp:

State value to set for "bambulab.0.00xxxxxxxxx.device.nozzle.0.temp" has to be type "string" but received type "number"

**Comment by Apropo1710** [comment]
Fehler leider immer noch vorhanden für den Big Fan beim P1S

`<html>
<body>

bambulab.2 | 2024-10-27 07:24:56.655 | info | State value to set for "bambulab.2.01P00A391400561.control.big_fan2_speed" has to be type "number" but received type "string"
-- | -- | -- | --
bambulab.2 | 2024-10-27 07:24:56.556 | info | State value to set for "bambulab.2.01P00A391400561.big_fan2_speed" has to be type "number" but received type "string"
bambulab.2 | 2024-10-27 07:24:53.186 | info | State value to set for "bambulab.2.01P00A391400561.control.big_fan2_speed" has to be type "number" but received type "string"
bambulab.2 | 2024-10-27 07:24:53.116 | info | State value to set for "bambulab.2.01P00A391400561.big_fan2_speed" has to be type "number" but received type "string"
bambulab.2 | 2024-10-27 07:24:47.345 | info | State value to set for "bambulab.2.01P00A391400561.control.big_fan2_speed" has to be type "number" but received type "string"


</body>
</html>`

**Comment by skvarel** [comment]
Die v0.2.3-bata.1 läuft bei meinem P1S ohne weitere Meldungen!

Danke, @DutchmanNL 👍

**Comment by DutchmanNL** [comment]
Bei dir ok @skvarel und bei @Apropo1710 wie kan das sein 😂

@Apropo1710 sicher das die neue Version installiert wurde?

**Comment by skvarel** [comment]
Ich habe garde während des Druck beide Lüfter (big-fan1 und big_fan2) hochgefahren. Die Datem kommen sauber im ioBroker an und der Log bleibt ruhig!

**Comment by skvarel** [comment]
@Apropo1710 .. hast du die v0.3.3-beta.1 getestet?

![grafik](https://github.com/user-attachments/assets/3c096d94-fb72-4006-8590-34f52c4fca29)

**Comment by FlexerJR** [comment]
Hallo @DutchmanNL 

freue mich tierisch, dass hier weitergemacht wird. Aktuell läuft die Beta ruhig. 

Ich schaue mal ob mir noch was an dem Adapter auffällt.

**Comment by DutchmanNL** [comment]
@FlexerJR vielen dank, wen alles stabiel ist würde ich ihn gerne nach stable bringen

**Comment by Apropo1710** [comment]
![image](https://github.com/user-attachments/assets/69850224-6644-49bd-af5e-7992290ae343)

**Comment by FlexerJR** [comment]
State value to set for "bambulab.0.00M09A3B1900317.control.big_fan2_speed" has to be type "number" but received type "string"

State value to set for "bambulab.0.00M09A3B1900317.big_fan2_speed" has to be type "number" but received type "string"

Kommt bei mir jetzt

**Comment by DutchmanNL** [comment]
sollte in der 0.3.3 final auch behoben sein @FlexerJR

**Comment by FlexerJR** [comment]
Perfekt wann kommt die 0.3.3? 

Ich habe da der Adapter nicht ging deaktiviert und stattdessen über Hass.io den Bambu in den Iob geholt. Soll ich dir ein paar Feature request machen? Da sind ein paar coole Sachen dabei.
