### ISSUE TITLE
Repeating error messages when the printer is off

### ISSUE THREAD

**Issue by SurfGargano** [DrozmotiX/ioBroker.bambulab#74]
**Describe the bug**  

If the printer is off, the protocol will be fulfilled with a lot of error messages , that the printer is unavailable. (Every 30 seconds)
Could this reduced and moved to warn level ? So I can set the procotol level to error.
Or even better implement a checkbox for protocol .

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by mcm1957** [comment]
duplicated by https://github.com/DrozmotiX/ioBroker.bambulab/issues/78
