### ISSUE TITLE
.. has to be type "number" but received type "string" 

### ISSUE THREAD

**Issue by skvarel** [DrozmotiX/ioBroker.bambulab#77]
Adapter Version : 0.3.2

![image](https://github.com/DrozmotiX/ioBroker.bambulab/assets/1114419/40412aa9-af71-43f6-ac93-2785ae673562)

**Comment by RoboCop0815** [comment]
ich habe das gleiche Problem...`State value to set for "bambulab.0.BambuLab.finishTime" has to be type "date" but received type "string"`

**Comment by RoboCop0815** [comment]
auch hier noch:
`<html><body>

bambulab.0 | 2024-01-14 16:06:40.016 | info | State value to set for "bambulab.0.01P00A3B2100920.control.big_fan2_speed" has to be type "number" but received type "string"
-- | -- | -- | --
bambulab.0 | 2024-01-14 16:06:28.872 | info | State value to set for "bambulab.0.01P00A3B2100920.control.big_fan2_speed" has to be type "number" but received type "string"
bambulab.0 | 2024-01-14 16:06:28.805 | info | State value to set for "bambulab.0.01P00A3B2100920.big_fan2_speed" has to be type "number" but received type "string"
bambulab.0 | 2024-01-14 16:06:17.604 | info | State value to set for "bambulab.0.01P00A3B2100920.control.big_fan2_speed" has to be type "number" but received type "string"
bambulab.0 | 2024-01-14 16:06:17.559 | info | State value to set for "bambulab.0.01P00A3B2100920.big_fan2_speed" has to be type "number" but received type "string"
bambulab.0 | 2024-01-14 16:06:07.479 | info | State value to set for "bambulab.0.01P00A3B2100920.control.big_fan2_speed" has to be type "number" but received type "string"


</body>
</html>`

**Comment by Bastler1971** [comment]
Habe selben Fehler bei finishTime, händisch ändern bringt nur kurze Zeit was

**Comment by vr6syncro** [comment]
ergänzend 

`<html>
<body>

bambulab.0 | 2024-05-26 11:49:13.624 | info | State value to set for "bambulab.0.XXX.finishTime" has to be type "date" but received type "string"
-- | -- | -- | --
bambulab.0 | 2024-05-26 11:49:13.582 | info | State value to set for "bambulab.0.XXX.device.nozzle.0.temp" has to be type "string" but received type "number"


</body>
</html>`

**Comment by MeisterQ** [comment]
Tut sich hier noch was? Das ist echt sehr nervig.

**Comment by DutchmanNL** [comment]
> Tut sich hier noch was? Das ist echt sehr nervig.

bitte version 0.3.3-beta.0 testen und bescheid geben :)

**Comment by Mima82** [comment]
Bekomme auch Ständige Protokolleinträge:

State value to set for "bambulab.0.01P00AXXXXX0006.k" has to be type "number" but received type "string"
