### ISSUE TITLE
Laufend Fehler- und WarnMeldungen nach dem Ausschalten des Bambu

### ISSUE THREAD

**Issue by RoboCop0815** [DrozmotiX/ioBroker.bambulab#78]
`<html><body>

bambulab.0 | 2024-01-29 08:05:28.138 | warn | Connection to Printer closed
-- | -- | -- | --
bambulab.0 | 2024-01-29 08:05:28.137 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:04:55.083 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:04:55.082 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:04:22.026 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:04:22.026 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:03:48.970 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:03:48.970 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:03:15.914 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:03:15.913 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:02:42.858 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:02:42.857 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:02:09.802 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:02:09.802 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:01:36.746 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:01:36.746 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883
bambulab.0 | 2024-01-29 08:01:03.690 | warn | Connection to Printer closed
bambulab.0 | 2024-01-29 08:01:03.689 | error | Connection issue occurred Error: connect EHOSTUNREACH 192.168.178.172:8883

</body>
</html>`
Bekomme laufend die Meldungen nachdem ich den Bambu Lab ausschalte.
Ich deaktiviere die Instanz vom Bambu Lab damit ich die Meldungen nicht erhalte, über ein Script.
Geht es auch anders?

**Comment by wendefeuer** [comment]
Mich nervt dass auch. Kann man vielleicht einen Schalter in der Adapter Konfig anlegen mit dem die Fehlermeldungen unterdrückt werden.

**Comment by Moormerlander** [comment]
Der Adapter wird seit etlichen Monaten nicht mehr upgedated und ist momentan leider völlig nutzlos weil ich keine aktuellen Stati sehe. Vielleicht baut mal jemand einen Adapter den man auch sinnvoll nutzen kann.

**Comment by Apollon77** [comment]
> Vielleicht baut mal jemand einen Adapter den man auch sinnvoll nutzen kann.

mach Doch ;-)

**Comment by Joylancer** [comment]
![grafik](https://github.com/user-attachments/assets/2bddd5f1-3081-41ed-8602-c56287cd268d)
