### ISSUE TITLE
Wird der Adapter nicht mehr gepflegt?

### ISSUE THREAD

**Issue by Moormerlander** [DrozmotiX/ioBroker.bambulab#88]
Der Adapter wird seit etlichen Monaten nicht mehr upgedated und ist momentan leider völlig nutzlos weil ich keine aktuellen Stati sehe. Vielleicht baut mal jemand einen Adapter den man auch sinnvoll nutzen kann.

**Comment by DutchmanNL** [comment]
> Der Adapter wird seit etlichen Monaten nicht mehr upgedated und ist momentan leider völlig nutzlos weil ich keine aktuellen Stati sehe. Vielleicht baut mal jemand einen Adapter den man auch sinnvoll nutzen kann.

es tut mir leid die gesundheit hat mir sehr zu schaffen gemacht wodurch einiges Stil gelegen hat.
Ich werde mein bestes tun die issue in den nässten doch ab zu arbeiten möchte aber auch nichts versprechen, aber tja er wird gepflegt leider nicht so frequent wie ich selber gerne moechte
