### ISSUE TITLE
Prevent message: Connection issue occurred Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by Azathoth88** [DrozmotiX/ioBroker.bambulab#99]
User Story: As a user, I would like to be able to prevent the message "Connection issue occurred Error: connect EHOSTUNREACH" via a checkbox in the instance settings in order to avoid receiving error messages in the log.
---
Side note: I usually switch off my printer when it is not in use. Currently, the message "Connection issue occurred Error: connect EHOSTUNREACH" appears every 30 seconds. This unnecessarily clutters up my log.

**Comment by mcm1957** [comment]
duplicate https://github.com/DrozmotiX/ioBroker.bambulab/issues/78
